<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * Functions used for database and table tracking
 *
 * @package PhpMyAdmin
 */
namespace PhpMyAdmin;

use PhpMyAdmin\Core;
use PhpMyAdmin\Message;
use PhpMyAdmin\Relation;
use PhpMyAdmin\Response;
use PhpMyAdmin\Sanitize;
use PhpMyAdmin\SqlQueryForm;
use PhpMyAdmin\Template;
use PhpMyAdmin\Tracker;
use PhpMyAdmin\Url;
use PhpMyAdmin\Util;

/**
 * PhpMyAdmin\Tracking class
 *
 * @package PhpMyAdmin
 */
class Tracking
{
    /**
     * Filters tracking entries
     *
     * @param array  $data           the entries to filter
     * @param string $filter_ts_from "from" date
     * @param string $filter_ts_to   "to" date
     * @param array  $filter_users   users
     *
     * @return array filtered entries
     */
    public static function filterTracking(
        array $data, $filter_ts_from, $filter_ts_to, array $filter_users
    ) {
        $tmp_entries = array();
        $id = 0;
        foreach ($data as $entry) {
            $timestamp = strtotime($entry['date']);
            $filtered_user = in_array($entry['username'], $filter_users);
            if ($timestamp >= $filter_ts_from
                && $timestamp <= $filter_ts_to
                && (in_array('*', $filter_users) || $filtered_user)
            ) {
                $tmp_entries[] = array(
                    'id'        => $id,
                    'timestamp' => $timestamp,
                    'username'  => $entry['username'],
                    'statement' => $entry['statement']
                );
            }
            $id++;
        }
        return($tmp_entries);
    }

    /**
     * Function to get html for data definition and data manipulation statements
     *
     * @param string $urlQuery    url query
     * @param int    $lastVersion last version
     * @param string $db          database
     * @param array  $selected    selected tables
     * @param string $type        type of the table; table, view or both
     *
     * @return string HTML
     */
    public static function getHtmlForDataDefinitionAndManipulationStatements(
        $urlQuery,
        $lastVersion,
        $db,
        array $selected,
        $type = 'both'
    ) {
        return Template::get('table/tracking/create_version')->render([
            'url_query' => $urlQuery,
            'last_version' => $lastVersion,
            'db' => $db,
            'selected' => $selected,
            'type' => $type,
            'default_statements' => $GLOBALS['cfg']['Server']['tracking_default_statements'],
        ]);
    }

    /**
     * Function to get html for activate/deactivate tracking
     *
     * @param string $action      activate|deactivate
     * @param string $urlQuery    url query
     * @param int    $lastVersion last version
     *
     * @return string HTML
     */
    public static function getHtmlForActivateDeactivateTracking(
        $action,
        $urlQuery,
        $lastVersion
    ) {
        return Template::get('table/tracking/activate_deactivate')->render([
            'action' => $action,
            'ery,
            'last_version' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'selrsion' => $lastVersion,
            'db' => $db,
            'sel    